name: kamilavardict
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - binutils_impl_linux-64=2.44=h4bf12b8_1
  - binutils_linux-64=2.44=h4852527_1
  - bwidget=1.10.1=ha770c72_1
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.16.0=h18b612c_1001
  - curl=7.68.0=hf8cf82a_0
  - fontconfig=2.14.1=hef1e5e3_0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=15.1.0=h4393ad2_4
  - gcc_linux-64=15.1.0=h1ac4077_11
  - gfortran_impl_linux-64=15.1.0=h3b9cdf2_4
  - gfortran_linux-64=15.1.0=h9e5855f_11
  - glib=2.80.2=hf974151_0
  - glib-tools=2.80.2=hb6ce0ca_0
  - graphite2=1.3.14=hecca717_1
  - gxx_impl_linux-64=15.1.0=h6a1bac1_4
  - gxx_linux-64=15.1.0=h1a088d8_11
  - harfbuzz=2.4.0=h37c48d4_1
  - icu=58.2=hf484d3e_1000
  - jpeg=9e=h0b41bf4_3
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - krb5=1.16.4=h2fd8d38_0
  - ld_impl_linux-64=2.44=h1423503_1
  - libcurl=7.68.0=hda55be3_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-devel_linux-64=15.1.0=h4c094af_104
  - libgcc-ng=15.1.0=h69a702a_4
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libgfortran5=15.1.0=hcea5267_4
  - libglib=2.80.2=hf974151_0
  - libgomp=15.1.0=h767d61c_4
  - libiconv=1.18=h4ce23a2_1
  - libpng=1.6.43=h2797004_0
  - libsanitizer=15.1.0=h97b714f_4
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-devel_linux-64=15.1.0=h4c094af_104
  - libstdcxx-ng=15.1.0=h4852527_4
  - libtiff=4.2.0=hf544144_3
  - libuuid=1.0.3=h7f8727e_2
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxml2=2.9.14=h74e7548_0
  - libzlib=1.2.13=h4ab18f5_6
  - make=4.4.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openjdk=11.0.1=h516909a_1016
  - openssl=1.1.1w=hd590300_0
  - pango=1.42.4=h7062337_4
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.43=hcad00b1_0
  - perl=5.26.2=h36c2ea0_1008
  - pixman=0.38.0=h516909a_1003
  - pthread-stubs=0.4=hb9d3cd8_1002
  - python=1.6=0
  - r-base=3.6.0=hce969dd_0
  - r-data.table=1.13.6=r36hcfec24a_0
  - readline=7.0=hf8c457e_1001
  - samtools=1.6=h244ad75_5
  - sysroot_linux-64=2.34=h087de78_2
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h8d826fa_7
  - tzdata=2025b=h78e105d_0
  - vardict=2019.06.04=pl526_0
  - vardict-java=1.5.8=0
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.2=h470a237_5
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0
prefix: /home/user/miniconda3/envs/kamilavardict
